[phases.setup]
nixPkgs = ["nodejs_20", "python3"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build --workspace=@repo/api", "npm run build --workspace=api"]

[start]
cmd = "node apps/api/dist/main.js"
