[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = [
    "cd ../.. && npm install --include=dev",
    "cd ../.. && npm run build --workspace=@repo/api",
    "cd ../.. && npm run build --workspace=api",
]

[start]
cmd = "cd ../.. && npm run start:prod --workspace=api"
